export interface PrestamoCancelaciones {
    c_compania?: string,
    c_prestamo?: string,
    n_linea?: number,
    d_fechavencimiento:	Date,
    n_montoprestamo?: string,
    n_montointereses?: string,
    c_tipocancelacion?: string,
    d_fechacancelacion?: Date,
    n_diastranscurridos?: string,
    n_montointeresesdiario?: string,
    n_montointeresescancelar?: string,
    n_montoprestamocancelar?: string,
    n_montocomisioncancelar?: string,
    n_montototalcancelar?: string,
    c_observacionescancelar?: string,
    c_estado?: string,
    c_usuarioregistro?: string,
    d_fecharegistro: Date,
    c_usuariocanceremat?: string,
    d_fechacanceremat: Date,
}